application: android-screenshots
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /.*
  script: screenshots.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name:    PIL
  version: latest